steps:
- name: 'docker'
  args: ['version']
  
- name: 'docker'
  args: ['build', '-t', 'us.gcr.io/playground-s-11-4d79e53e/javier-python:latest', '.']
images: ['us.gcr.io/playground-s-11-4d79e53e/javier-python:latest']
