steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/JavierBaltar/cloud-build-demo', '.']
  
- name: 'docker'
  args: ['build', '-t', 'us.gcr.io/playground-s-11-4d79e53e/javier-python:latest', '.']
images: ['us.gcr.io/playground-s-11-4d79e53e/javier-python:latest']
